package DDE;

public enum DDECellsEnum {
    IND, IND_BID, IND_ASK, FUT_MONTH, FUT_MONTH_BID, FUT_MONTH_ASK, E1, FUT_QUARTER_BID, FUT_QUARTER_ASK, OPEN, HIGH, LOW, BASE, INDEX_MOVE_15, FUT_WEEK, E2, FUT_DAY;
}
